name: qaweb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.5
  youtube_player_flutter: ^9.1.1
  youtube_player_iframe: ^5.2.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  supabase_flutter: ^2.9.0
  gotrue: ^2.12.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - "assets/neet.jpg"
