// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWJpduYYo2b2INr3dCwDnUZjLFzUz7wgo',
    appId: '1:120744589773:web:2e71f7c45510d244da2c84',
    messagingSenderId: '120744589773',
    projectId: 'lios-108e0',
    authDomain: 'lios-108e0.firebaseapp.com',
    storageBucket: 'lios-108e0.firebasestorage.app',
    measurementId: 'G-198MWLM5FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmZhwdCGP_DWoMvFSTB8Uacqy0L_UlGms',
    appId: '1:120744589773:android:8fad35c8507ca452da2c84',
    messagingSenderId: '120744589773',
    projectId: 'lios-108e0',
    storageBucket: 'lios-108e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3nHypK7vEdER2yqHN72WbLGe4iKGszFg',
    appId: '1:120744589773:ios:90b01203c4dfb6fbda2c84',
    messagingSenderId: '120744589773',
    projectId: 'lios-108e0',
    storageBucket: 'lios-108e0.firebasestorage.app',
    iosBundleId: 'com.example.qaweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3nHypK7vEdER2yqHN72WbLGe4iKGszFg',
    appId: '1:120744589773:ios:90b01203c4dfb6fbda2c84',
    messagingSenderId: '120744589773',
    projectId: 'lios-108e0',
    storageBucket: 'lios-108e0.firebasestorage.app',
    iosBundleId: 'com.example.qaweb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWJpduYYo2b2INr3dCwDnUZjLFzUz7wgo',
    appId: '1:120744589773:web:68118da96bc453abda2c84',
    messagingSenderId: '120744589773',
    projectId: 'lios-108e0',
    authDomain: 'lios-108e0.firebaseapp.com',
    storageBucket: 'lios-108e0.firebasestorage.app',
    measurementId: 'G-YF7NNR16E7',
  );
}
